config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts

  root "posts#index", as: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class LinkValidator < ActiveModel::Validator
  def validate(record)

    #format = "https://"
  end
end

class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :author, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 30, maximum: 400 }
  validates :image, :link, format: { with: /[http:]/, message: "filled in incorrectly" }

  validates_with LinkValidator, fields: [:author]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def intex

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, :correct_user, :only => [:new, :edit, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @special_user = User.first
    @super_user_email = "Bohdanvah@gmail.com"
  end

  def correct_user
    @post = Post.find_by(id: params[:id])  # find the post
  end

  # GET /posts/1 or /posts/1.json
  def show
    @super_user_email = "Bohdanvah@gmail.com"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @special_user = User.first
    @super_user_email = "Bohdanvah@gmail.com"
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :image, :description, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render template: "components/_navbar" %>

    <div class="container">

      <% if notice %>
        <p class="alert alert-success mt-5"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="mb-3">
    <%= form.label :title, style: "display: block", class:"form-label" %>
    <%= form.text_field :title, class:"form-control", placeholder: 'Project #1' %>
  </div>

  <div class="mb-3">
    <%= form.label :author, style: "display: block", class:"form-label" %>
    <%= form.text_field :author, class:"form-control", placeholder: 'Carl Johnson' %>
  </div>

  <div class="mb-3">
    <%= form.label :image, "Image URL", style: "display: block", class:"form-label" %>
    <%= form.text_field :image, class:"form-control", placeholder: 'http://image_url' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class:"form-label" %>
    <%= form.text_field :description, class:"form-control", placeholder: 'Short story about this project' %>
  </div>

  <div class="mb-3">
    <%= form.label :link, style: "display: block", class:"form-label" %>
    <%= form.text_field :link, class:"form-control", placeholder: 'http://project_url' %>
  </div>

  <% if post.errors.any? %>
    <div style="color: red">
      <h4><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>

      </ul>
    </div>
  <% end %>

  <div class="d-flex justify-content-center">
    <%= form.submit class:"btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <%= post.title %>
  </p>

  <p>
    <img src="<%= post.image %>" style="width:100%; height:300px; object-fit: cover;">
  </p>

  <div class="d-flex justify-content-between align-items-center">
    <p>
      <strong>@<%= post.author %></strong>
    </p>
    <p style="font-size: 12px;">
      <%= post.created_at.strftime("%d %B %Y") %>
    </p>
  </div>

  <p>
      <%= post.description %>
    </p>

  <% if post.link.empty? %>
    <p></p>
  <% else %>
    <p style="margin-bottom: 80px">
      <a href="<%= post.link %>" target="_blank">Check the link attached by the author</a>
    </p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class="d-flex gap-3 mb-5">
<% if current_user %>
  <% if current_user.email.downcase != @super_user_email.downcase %>
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-primary" %>
    <%= current_user.email %>
  <% else %>
    <%= link_to "Show this post", @post, class:"btn btn-outline-primary" %>
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-primary" %>
  <% end %>
<% end %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div id="posts" class="">
    <% if @posts.empty? %>
      <h2 class="text-center mt-5 mb-5">No posts yet</h2>

    <% else %>
    <hr />
      <div class="row row-cols-3">
        <% @posts.each do |post| %>
          <div class="col" style="position:relative">
            <%= render post %>
            <p style="position:absolute; bottom:0px">
              <%= link_to "Show details", post, class:"btn btn-secondary" %>
            </p>
          </div>
        <% end %>
        </div>
      <hr />
    <% end %>
</div>

<% if current_user %>
  <% if current_user.email.downcase != @super_user_email.downcase and current_user.email.downcase != @special_user.email.downcase %>

    <p class="text-center" style="color:#7B8FA1;">
    We noticed that you are not our admin. Only the view option is available to you.
    </p>
  <% else %>
    <% if @posts.empty? %>
      <p class="text-center mt-5 mb-5">Add your first post</p>
    <% else %>
      <p class="text-center mt-5 mb-5">Add new post</p>
    <% end %>
    <div class="d-flex justify-content-center">
      <%= link_to "Add post", new_post_path, class:"btn btn-primary mt-5 mb-5" %>
    </div>
  <% end %>
<% else %>
    <p class="text-center" style="color:#7B8FA1;">
      Who are you stranger? Looks like you are not authorized. Only the view option is available to you.
    </p>
<% end %>

app/views/posts/new.html.erb
<h1 class="text-center mb-5">New post</h1>

<%= render "form", post: @post %>

<br>

<div class="d-flex justify-content-center">
  <%= link_to "Back to posts", posts_path, class:"link-secondary text-center mb-5" %>
</div>

app/views/posts/show.html.erb
<div>
  <img src="<%= @post.image %>" class="mb-5" style="width:100%; max-height:500px; object-fit: cover;">
  <div class="d-flex justify-content-between align-items-center">
    <h1 class="mb-3"><%= @post.title %></h1>
    <h6><strong>By @<%= @post.author %></strong></h6>
  </div>
  <p><%= @post.description %></p>
  <p style="font-size:12px"><%= @post.created_at.strftime("%d %B %Y") %></p>
</div>

<% if current_user %>
  <% if current_user.email.downcase != @super_user_email.downcase %>
    <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary mb-5" %>
  <% else %>
    <div class="d-flex justify-content-between align-items-center mt-5 mb-5">
      <div class="d-flex gap-5">
        <%= link_to "Edit", edit_post_path(@post), class:"btn btn-outline-secondary" %>
        <%= link_to "Back to posts", posts_path, class:"btn btn-outline-secondary" %>
      </div>

      <%= button_to "Delete", @post, method: :delete, data: {turbo_method: :delete,
      turbo_confirm: 'Are you sure you want to delete this post?'}, class:"btn btn-danger" %>
    </div>
  <% end %>
<% end %>